### ISSUE TITLE
Locale fa not found. Did you forget to load it?

### ISSUE THREAD

**Issue by mazyar** [jalaali/moment-jalaali#131]
Hi,
show a warning message in browser when use momnet-jalaali in react js
the message shown when write below code
` moment.loadPersian();    `

**Comment by eagle-design** [comment]
سلام من هم در حالت عادی این مشکل رو دارم
همه چیز اوکی هست فقط این وارنینگ میاد
Locale fa not found. Did you forget to load it?

**Comment by salaaar** [comment]
Change moment JS api casues this issue, Fixed in comment below: 
[](https://github.com/salaaar/moment-jalaali/commit/e068c9b55ed9fe23d3c90eb7d5698068b955784b)

**Comment by AE0011** [comment]
@alitaheri 
i'm using  `"moment-jalaali": "^0.8.1",` this version still not work (android 4.2.2 release mode)
`Requiring unknown module "./locale/fa"`
